version: '3.5'

services:
  vartalogger:
    build: .
    environment:
      - INFLUXDB_URL=http://influxdb:8086/
      - VARTA_BASE_URL=http://fakeVartaBattery:80/
      - INFLUXDB_BUCKET=varta
      - INFLUXDB_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
      - MEASUREMENT_KEY=battery
      - MEASUREMENT_FREQUENCY_IN_SECONDS=3
  fakeVartaBattery:
    image: nginx:latest
    ports:
      - '8001:80'
    volumes:
      - ./mockVartaBatteryApi:/usr/share/nginx/html
  influxdb:
    image: influxdb:1.7.4
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=testing
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLXUDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  chronograf:
    image: "chronograf:1.7.8"
    ports:
      - 8888:8888
    depends_on:
      - influxdb
volumes:
  influxdb-storage:
